version: '2.4'

services:
  app:
    image: node:14-alpine
    ports:
      - 3000:3000
    volumes:
      - .:/var/app
    working_dir: /var/app
    command: npm start
  
  build:
    image: node:14-alpine
    volumes:
      - .:/var/app
    working_dir: /var/app
    command: npm run build

  tests:
    image: node:14-alpine
    ports:
      - 3000:3000
    volumes:
      - .:/var/app
    working_dir: /var/app
    command: sh -c "npm install && npm run test"

  deps:
    image: node:14-alpine
    volumes:
      - .:/var/app
    working_dir: /var/app
    command: sh -c "npm install"
